### ISSUE TITLE
packImages doesn't use the output name

### ISSUE THREAD

**Issue by screwdycrow** [oumad/proton-io#1]
**Description of the bug**

When i try to apply the packImages script using some combination of strings in the output name field, the script saves the pack with the format type as name isntead. 
ex: png.png

If i leave this blank it saves the pack with the name package which i guess is the right behaviour.

**Steps to reproduce the bug**

select any number of images, open packImages, enter any string as output name hit apply.

**Comment by oumad** [comment]
The fixed script can be downloaded directly from the repo for now.
