### ISSUE TITLE
composite output name is not working.

### ISSUE THREAD

**Issue by screwdycrow** [oumad/proton-io#2]
**description of the bug**
When i try to save a composition of some selected images with a specified name, it remains as "[name of file]_plus.png, in case i used the plus blend and png format, which i guess is the default behaviour.

**steps to reproduce it** 
Select some number of images, open composite, fill the output name, and hit apply.

**Comment by oumad** [comment]
I just fixed this script, you can can get the last version in the repo for now until I release a new update with other fixes.
