### ISSUE TITLE
solidColour output name doesnt work

### ISSUE THREAD

**Issue by screwdycrow** [oumad/proton-io#3]
**Description of the bug**
The name of outputed file when using the solid colour script remains solid.jpeg (when i use jpeg as format)

**Steps to reproduce**
select one image, open solid Colour script fill the output name and hit apply.

**Comment by oumad** [comment]
I can't reproduce this one, the output name works fine for me with the solidColor script.

**Comment by oumad** [comment]
I'm closing this for now since we can't reproduce it.
