### ISSUE TITLE
Output Directory doesnt work on specific image processing scripts.

### ISSUE THREAD

**Issue by screwdycrow** [oumad/proton-io#4]
**description**
On all the image scripts except the solidColour, when i specify an output Directory, it outputs the file on the current folder instead.

**Steps to reproduce**
select some images, open any image proccessing script except solidColour, fill the output directory field, hit apply

**Comment by oumad** [comment]
I just fixed this, in the mean time you can get these scripts from the repo until I compile a new version of proton-io with other bug fixes.
